apiVersion: v1
kind: Service
metadata:
  name: carts
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: carts
  namespace: sock-shop
spec:
  type: LoadBalancer   # Change the type to LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: carts
