apiVersion: v1
kind: Service
metadata:
  name: carts-db
  labels:
    name: carts-db
  namespace: sock-shop
spec:
  type: LoadBalancer   # Change the type to LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: carts-db
