name: Kubernetes Deployment to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update kube config 
      env:
        CLUSTER_NAME: eks-cluster    
      run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region us-east-1
    
    - name: Set up monitoring
      run: kubectl apply -f manifests-monitoring/    
    