name: Kubernetes Deployment to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kube config 
      run: aws eks update-kubeconfig --name eks-cluster --region us-east-1

    - name: Set up monitoring
      run: kubectl apply -f manifests-monitoring/    
    
    - name: Set up logging
      run: kubectl apply -f manifests-logging/ 
    
    - name: Set up nginx-controller
      run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/cloud/deploy.yaml
    
    - name: Set up CRD
      run: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
    
    - name: Set up manifests
      run: kubectl apply -f manifests/ 

    - name: Set up ingress
      run: kubectl apply -f ingress/  